### ISSUE TITLE
Does not start the app.

### ISSUE THREAD

**Issue by aadriankoxha** [hobbydevs/InstabotJS#1]
$ node -v
v8.11.4

Adrian@DESKTOP-HQDJ67V MINGW64 /c/xampp/htdocs/InstabotJS/build (master)
$ node main.js
module.js:549
    throw err;
    ^

Error: Cannot find module 'C:\xampp\htdocs\InstabotJS\build\main.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

**Comment by hobbydevs** [comment]
the main.js file is under build/**src**/
So you need to go to InstabotJS/build/src/ and then type the command ‚node main.js‘

**Comment by aadriankoxha** [comment]
Adrian@DESKTOP-HQDJ67V MINGW64 /c/xampp/htdocs/InstabotJS/build/src (master)
$ node main.js
TypeError: this.storageService.getUnfollowed is not a function
    at Instabot.collectPreviousData
(C:\xampp\htdocs\InstabotJS\build\src\models
\bot.js:104:47)
    at Instabot.<anonymous>
(C:\xampp\htdocs\InstabotJS\build\src\models\bot.js:
69:22)
    at Generator.next (<anonymous>)
    at C:\xampp\htdocs\InstabotJS\node_modules\tslib\tslib.js:107:75
    at new Promise (<anonymous>)
    at Object.__awaiter
(C:\xampp\htdocs\InstabotJS\node_modules\tslib\tslib.js:
103:16)
    at Instabot.initBot
(C:\xampp\htdocs\InstabotJS\build\src\models\bot.js:63:2
4)
    at C:\xampp\htdocs\InstabotJS\build\src\main.js:15:10
    at Object.<anonymous>
(C:\xampp\htdocs\InstabotJS\build\src\main.js:23:3)
    at Module._compile (module.js:652:30)


it happens again

**Comment by hobbydevs** [comment]
Let me look into it, repoening the issue

**Comment by aadriankoxha** [comment]
Hey yes I did npm install lets see once again lol thanks for the help

**Comment by hobbydevs** [comment]
seems like the issue is fixed. Feel free to open again if issue is still present.
